---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c molecule/default/.yamllint .
<<<<<<< HEAD
#  ansible-lint -x meta-incorrect,meta-no-info,package-latest,yaml
=======
#ansible-lint -x meta-incorrect,meta-no-info,package-latest,yaml
>>>>>>> 2bdd0f55e5c120d62f00efe7e3942a3f62ebf75f
platforms:
  - name: instance-centos
    image: "eazytraining/diveintoansible:centos"
    command: "/lib/systemd/systemd"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: instance-ubuntu
    image: "eazytraining/diveintoansible:ubuntu"
    command: "/lib/systemd/systemd"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
